---
- name: Check and install firewall related packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install 'ufw' package
      apt:
        name: ufw
        state: present

    - name: Enable and start 'ufw' service
      systemd:
        name: ufw
        enabled: yes
        state: started

    - name: Check 'ufw' status
      command: ufw status
      register: ufw_status
      ignore_errors: yes

    - name: Display 'ufw' status
      debug:
        var: ufw_status.stdout

    - name: Display message if firewall is off
      debug:
        msg: "Firewall is off. You may want to configure your firewall rules."
      when: '"Status: inactive" in ufw_status.stdout'

- name: Save 'ufw' status to a JSON file
  hosts: localhost
  tasks:
    - name: Save 'ufw' status to a JSON file
      copy:
        content: "{{ ufw_status.stdout | to_json }}"
        dest: /home/fabio/Workspace/data.json


      test commit from root directory 
